# Generated by Django 5.2.15 on 2026-07-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0019_alter_dogmaattribute_name_and_more'),
        ('outfit418_backup_ratting', '0005_eventbackup_eventmemberbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterauditlogindata',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characterauditlogindata',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characterauditlogindata',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('login_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_activity', to='outfit418_backup_ratting.characterauditlogindata')),
            ],
        ),
        migrations.CreateModel(
            name='MemberActivityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('member_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='outfit418_backup_ratting.memberactivity')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='eve_sde.solarsystem')),
            ],
        ),
    ]
