# Generated by Django 5.2.15 on 2026-07-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit418_backup_ratting', '0006_characterauditlogindata_is_online_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('audit_corp', "Can audit corp members' alts"), ('find_jeremy', 'Can find Jeremy'), ('view_member_activity', 'Can view member activity'))},
        ),
    ]
