# Generated by Django 5.2.15 on 2026-07-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit418_backup_ratting', '0007_alter_general_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberactivitylocation',
            name='is_docked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
